from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd + '/../inc']

group = DefineGroup('masan', src, depend = ['PKG_USING_MASAN'], CPPPATH = CPPPATH)

Return('group')
